variables:
  DOCKER_HOST: tcp://docker:2375

services:
  - docker:stable-dind

stages:
  - build
  - test

include:
  # Tunnel integration with GitLab Container Scanning
  - remote: "https://github.com/khulnasoft/tunnel/raw/main/contrib/Tunnel.gitlab-ci.yml"

build:
  image: docker:stable
  stage: build
  variables:
    IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
  script:
    - docker info
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $IMAGE .
    - docker push $IMAGE

# This overriding is not mandatory for GitLab Securty Scanning Report integration
# and is mainly for a demonstration how it works on GitLab Community Edition
Tunnel_container_scanning:
  artifacts:
    paths: [gl-container-scanning-report.json]
