orbs:
  node: circleci/node@5.1.0
jobs:
  build:
    docker:
      - image: docker:18.09-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build image
          command: docker build -t tunnel-ci-test:${CIRCLE_SHA1} .
      - run:
          name: Install tunnel
          command: |
            apk add --update-cache --upgrade --update curl
            curl -sfL https://raw.githubusercontent.com/khulnasoft/tunnel/main/contrib/install.sh | sh -s -- -b /usr/local/bin
      - run:
          name: Scan the local image with tunnel (light)
          command: tunnel --exit-code 0 --no-progress tunnel-ci-test:${CIRCLE_SHA1}
workflows:
  version: 2
  release:
    jobs:
      - build
