name: Scan
on: [push, pull_request]
jobs:
  scan:
    name: Scan
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Test
      run: docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v $PWD:/tmp/.cache/ khulnasoft/tunnel:latest alpine:3.10.2
    - name: Build
      run: docker build -t tunnel-ci-test:1.2.3 .
    - name: Scan
      uses: docker://khulnasoft/tunnel
      with:
        args: --severity CRITICAL --no-progress tunnel-ci-test:1.2.3
